name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
      - name: Build poetry
        run: pip install poetry && poetry build
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV AWS
        run: echo 'DEV Deploy'
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA AWS
        run: echo 'QA Deploy'